### ISSUE TITLE
Optimize boolean to be added manually

### ISSUE THREAD

**Issue by plompd** [timw255/timw255.Sitefinity.ImageOptimization#1]
Is it correct that I needed to add the 'Optimize' boolean to the Image custom fields? It couldn't execute this method:

```
public virtual int GetItemsCount(Guid albumId)
    {
        return LibManager.GetAlbum(albumId).Images().Where(i => i.Status == ContentLifecycleStatus.Master && !i.GetValue<bool>("Optimized")).Count();
    }
```

After adding the field, it executes fine.

**Comment by galeassim** [comment]
The dev branch has removed the dependency on the custom field.

**Comment by timw255** [comment]
@konstrui It was impossible to reliably keep track of the optimization status of an item so, flagging optimized images was moved from a field on the actual item to an ImageOptimizationLogEntry.

I totally spaced on updating master though. Thanks for the heads up!

**Comment by timw255** [comment]
Merged
